name: Deploy HTML Website to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to cPanel
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: 22
          source: "./*"
          target: "/home/hokkaido/public_html/"
          strip_components: 1